server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:roomsdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update        # dev-only; for prod use validate + migrations
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
